package generator

import "fmt"

func (gen *caGen) GenEnv() error {
	configEnv := []byte(`DB_USER_TEST=root
DB_PASSWORD_TEST=root
DB_NAME_TEST=test
GIN_MODE=release

DATABASE_HOST_PG=127.0.0.1
DATABASE_PORT_PG=5432
DATABASE_USER_PG=root
DATABASE_PASSWORD_PG=root
DATABASE_NAME_PG=ca_cli

DATABASE_HOST_MYSQL=127.0.0.1
DATABASE_PORT_MYSQL=3306
DATABASE_USER_MYSQL=root
DATABASE_PASSWORD_MYSQL=
DATABASE_NAME_MYSQL=ca_cli

SERVER_ECHO_PORT=9090
SERVER_GIN_PORT=8090
SERVER_GORILLA_MUX_PORT=7090
SERVER_NET_HTTP_SERVER_MUX_PORT=6090
SERVER_GRAPHQL_SERVER_MUX_PORT=5090
SERVER_GRPC_PORT=50051`)

	fmt.Println(configEnv)
	return nil
}
